squad-stats-report: fix json.dump traceback
Running squad-stats-report gives the following 'Traceback':
Traceback (most recent call last):
 File "/home/anders/src/auto-squad-client-utils/./squad-stats-report", line 430, in <module>
  sys.exit(run())
       ^^^^^
 File "/home/anders/src/auto-squad-client-utils/./squad-stats-report", line 376, in run
  Path(filename).write_text(json.dump(a, indent=4), encoding="utf-8")
                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: dump() missing 1 required positional argument: 'fp'

Use json.dumps() instead.

Fixes: a0ffae489373 ("squad-stats-report: read/write directly without a fd")
Suggested-by: Charles Oliveira <charles.oliveira@linaro.org>
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>